head(USJudgeRatings)
USJudgeRatings = subset(USJudgeRatings, select = -c (dumm1,dumm2,dumm3))
bertinplot(as.matrix(USJudgeRatings))
mydf <- as.data.frame(USJudgeRatings)
colnames(mydf)
x <- subset(mydf, select = c(CONT,INTG,DMNR,DILG,CFMG,DECI,PREP,FAMI,ORAL,WRIT,PHYS,RTEN))
scale_by_rank <- function(x) apply(x, 2, rank) 
x <- scale_by_rank(USJudgeRatings[,-6]) 
order <- c( seriate(dist(x, "minkowski", p = 1)), seriate(dist(t(x), "minkowski", p = 1)) ) 
bertinplot(x, order)
